# TCL File Generated by Component Editor 17.1
# Wed Feb 28 19:03:09 ICT 2018
# DO NOT MODIFY


# 
# RamSrc "RamSrc" v1.0
#  2018.02.28.19:03:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module RamSrc
# 
set_module_property DESCRIPTION ""
set_module_property NAME RamSrc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME RamSrc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RamSrc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RamSrc.v VERILOG PATH RamSrc.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter B INTEGER 32
set_parameter_property B DEFAULT_VALUE 32
set_parameter_property B DISPLAY_NAME B
set_parameter_property B TYPE INTEGER
set_parameter_property B UNITS None
set_parameter_property B HDL_PARAMETER true
add_parameter W INTEGER 10
set_parameter_property W DEFAULT_VALUE 10
set_parameter_property W DISPLAY_NAME W
set_parameter_property W TYPE INTEGER
set_parameter_property W UNITS None
set_parameter_property W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 write_n write_n Input 1
add_interface_port s1 writedata writedata Input B
add_interface_port s1 address address Input W
add_interface_port s1 readdata readdata Output B
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rd_addr
# 
add_interface rd_addr conduit end
set_interface_property rd_addr associatedClock clock
set_interface_property rd_addr associatedReset ""
set_interface_property rd_addr ENABLED true
set_interface_property rd_addr EXPORT_OF ""
set_interface_property rd_addr PORT_NAME_MAP ""
set_interface_property rd_addr CMSIS_SVD_VARIABLES ""
set_interface_property rd_addr SVD_ADDRESS_GROUP ""

add_interface_port rd_addr rd_addr name Input W


# 
# connection point rd_data
# 
add_interface rd_data conduit end
set_interface_property rd_data associatedClock clock
set_interface_property rd_data associatedReset ""
set_interface_property rd_data ENABLED true
set_interface_property rd_data EXPORT_OF ""
set_interface_property rd_data PORT_NAME_MAP ""
set_interface_property rd_data CMSIS_SVD_VARIABLES ""
set_interface_property rd_data SVD_ADDRESS_GROUP ""

add_interface_port rd_data rd_data name Output B


# 
# connection point oe
# 
add_interface oe conduit end
set_interface_property oe associatedClock clock
set_interface_property oe associatedReset ""
set_interface_property oe ENABLED true
set_interface_property oe EXPORT_OF ""
set_interface_property oe PORT_NAME_MAP ""
set_interface_property oe CMSIS_SVD_VARIABLES ""
set_interface_property oe SVD_ADDRESS_GROUP ""

add_interface_port oe oe name Input 1

